version: 2
updates:
- package-ecosystem: gomod
  directory: "/provider"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 3
  reviewers:
  - ringods
- package-ecosystem: gomod
  directory: "/sdk"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 3
  reviewers:
  - ringods
