// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Concourse
{
    [ConcourseResourceType("concourse:index/team:Team")]
    public partial class Team : Pulumi.CustomResource
    {
        [Output("members")]
        public Output<ImmutableArray<string>> Members { get; private set; } = null!;

        [Output("owners")]
        public Output<ImmutableArray<string>> Owners { get; private set; } = null!;

        [Output("pipelineOperators")]
        public Output<ImmutableArray<string>> PipelineOperators { get; private set; } = null!;

        [Output("teamName")]
        public Output<string> TeamName { get; private set; } = null!;

        [Output("viewers")]
        public Output<ImmutableArray<string>> Viewers { get; private set; } = null!;


        /// <summary>
        /// Create a Team resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Team(string name, TeamArgs args, CustomResourceOptions? options = null)
            : base("concourse:index/team:Team", name, args ?? new TeamArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Team(string name, Input<string> id, TeamState? state = null, CustomResourceOptions? options = null)
            : base("concourse:index/team:Team", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/pulumiverse/pulumi-concourse/releases/download/${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Team resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Team Get(string name, Input<string> id, TeamState? state = null, CustomResourceOptions? options = null)
        {
            return new Team(name, id, state, options);
        }
    }

    public sealed class TeamArgs : Pulumi.ResourceArgs
    {
        [Input("members")]
        private InputList<string>? _members;
        public InputList<string> Members
        {
            get => _members ?? (_members = new InputList<string>());
            set => _members = value;
        }

        [Input("owners", required: true)]
        private InputList<string>? _owners;
        public InputList<string> Owners
        {
            get => _owners ?? (_owners = new InputList<string>());
            set => _owners = value;
        }

        [Input("pipelineOperators")]
        private InputList<string>? _pipelineOperators;
        public InputList<string> PipelineOperators
        {
            get => _pipelineOperators ?? (_pipelineOperators = new InputList<string>());
            set => _pipelineOperators = value;
        }

        [Input("teamName", required: true)]
        public Input<string> TeamName { get; set; } = null!;

        [Input("viewers")]
        private InputList<string>? _viewers;
        public InputList<string> Viewers
        {
            get => _viewers ?? (_viewers = new InputList<string>());
            set => _viewers = value;
        }

        public TeamArgs()
        {
        }
    }

    public sealed class TeamState : Pulumi.ResourceArgs
    {
        [Input("members")]
        private InputList<string>? _members;
        public InputList<string> Members
        {
            get => _members ?? (_members = new InputList<string>());
            set => _members = value;
        }

        [Input("owners")]
        private InputList<string>? _owners;
        public InputList<string> Owners
        {
            get => _owners ?? (_owners = new InputList<string>());
            set => _owners = value;
        }

        [Input("pipelineOperators")]
        private InputList<string>? _pipelineOperators;
        public InputList<string> PipelineOperators
        {
            get => _pipelineOperators ?? (_pipelineOperators = new InputList<string>());
            set => _pipelineOperators = value;
        }

        [Input("teamName")]
        public Input<string>? TeamName { get; set; }

        [Input("viewers")]
        private InputList<string>? _viewers;
        public InputList<string> Viewers
        {
            get => _viewers ?? (_viewers = new InputList<string>());
            set => _viewers = value;
        }

        public TeamState()
        {
        }
    }
}
