// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("concourse");

/**
 * Password, do not use if using target
 */
export declare const password: string | undefined;
Object.defineProperty(exports, "password", {
    get() {
        return __config.get("password");
    },
    enumerable: true,
});

/**
 * Target as in 'fly --target', do not use if using team/username/password
 */
export declare const target: string | undefined;
Object.defineProperty(exports, "target", {
    get() {
        return __config.get("target");
    },
    enumerable: true,
});

/**
 * Team name, do not use if using target
 */
export declare const team: string | undefined;
Object.defineProperty(exports, "team", {
    get() {
        return __config.get("team");
    },
    enumerable: true,
});

/**
 * URL, do not use if using target
 */
export declare const url: string | undefined;
Object.defineProperty(exports, "url", {
    get() {
        return __config.get("url");
    },
    enumerable: true,
});

/**
 * Username, do not use if using target
 */
export declare const username: string | undefined;
Object.defineProperty(exports, "username", {
    get() {
        return __config.get("username");
    },
    enumerable: true,
});

