# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('concourse')


class _ExportableConfig(types.ModuleType):
    @property
    def password(self) -> Optional[str]:
        """
        Password, do not use if using target
        """
        return __config__.get('password')

    @property
    def target(self) -> Optional[str]:
        """
        Target as in 'fly --target', do not use if using team/username/password
        """
        return __config__.get('target')

    @property
    def team(self) -> Optional[str]:
        """
        Team name, do not use if using target
        """
        return __config__.get('team')

    @property
    def url(self) -> Optional[str]:
        """
        URL, do not use if using target
        """
        return __config__.get('url')

    @property
    def username(self) -> Optional[str]:
        """
        Username, do not use if using target
        """
        return __config__.get('username')

