// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

/**
 * Get step
 */
export interface GetArgs {
    identifier: pulumi.Input<string>;
}

/**
 * Job configuration
 */
export interface JobArgs {
    identifier: pulumi.Input<string>;
    plan: pulumi.Input<pulumi.Input<inputs.GetArgs | inputs.PutArgs | inputs.TaskArgs>[]>;
}

/**
 * Pipeline configuration
 */
export interface PipelineConfigArgs {
    jobs: pulumi.Input<pulumi.Input<inputs.JobArgs>[]>;
}

/**
 * Put step
 */
export interface PutArgs {
    identifier: pulumi.Input<string>;
}

/**
 * Task step
 */
export interface TaskArgs {
    identifier: pulumi.Input<string>;
}
