// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace tejavar.Concourse.Inputs
{

    /// <summary>
    /// Job configuration
    /// </summary>
    public sealed class JobArgs : global::Pulumi.ResourceArgs
    {
        [Input("identifier", required: true)]
        public Input<string> Identifier { get; set; } = null!;

        [Input("plan", required: true)]
        private InputList<object>? _plan;
        public InputList<object> Plan
        {
            get => _plan ?? (_plan = new InputList<object>());
            set => _plan = value;
        }

        public JobArgs()
        {
        }
        public static new JobArgs Empty => new JobArgs();
    }
}
