// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Concourse.Inputs
{

    /// <summary>
    /// Pipeline configuration
    /// </summary>
    public sealed class PipelineConfigArgs : Pulumi.ResourceArgs
    {
        [Input("jobs", required: true)]
        private InputList<Inputs.JobArgs>? _jobs;
        public InputList<Inputs.JobArgs> Jobs
        {
            get => _jobs ?? (_jobs = new InputList<Inputs.JobArgs>());
            set => _jobs = value;
        }

        public PipelineConfigArgs()
        {
        }
    }
}
