// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Pulumiverse.Concourse.Inputs
{

    /// <summary>
    /// Task step
    /// </summary>
    public sealed class TaskArgs : global::Pulumi.ResourceArgs
    {
        [Input("identifier", required: true)]
        public Input<string> Identifier { get; set; } = null!;

        public TaskArgs()
        {
        }
        public static new TaskArgs Empty => new TaskArgs();
    }
}
