name: main

on:
  push:
    branches:
      - main
    tags-ignore:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  prerequisites:
    permissions:
      pull-requests: write
    uses: tejavar/infra/.github/workflows/provider-prerequisites.yaml@actions-workflows-v0.0.4
    with:
      provider: concourse
      goversion: 1.20.x
  build:
    needs: prerequisites
    uses: tejavar/infra/.github/workflows/provider-build-sdk.yaml@actions-workflows-v0.0.4
    with:
      provider: concourse
      goversion: 1.20.x
      dotnetversion: 6.0
      nodeversion: 16.x
      pythonversion: 3.8
