# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .pipeline import *
from .provider import *
from ._inputs import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "concourse",
  "mod": "index",
  "fqn": "pulumiverse_concourse",
  "classes": {
   "concourse:index:Pipeline": "Pipeline"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "concourse",
  "token": "pulumi:providers:concourse",
  "fqn": "pulumiverse_concourse",
  "class": "Provider"
 }
]
"""
)
