# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .get_pipeline import *
from .get_team import *
from .get_teams import *
from .pipeline import *
from .provider import *
from .team import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumiverse_concourse.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumiverse_concourse.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "concourse",
  "mod": "index/pipeline",
  "fqn": "pulumiverse_concourse",
  "classes": {
   "concourse:index/pipeline:Pipeline": "Pipeline"
  }
 },
 {
  "pkg": "concourse",
  "mod": "index/team",
  "fqn": "pulumiverse_concourse",
  "classes": {
   "concourse:index/team:Team": "Team"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "concourse",
  "token": "pulumi:providers:concourse",
  "fqn": "pulumiverse_concourse",
  "class": "Provider"
 }
]
"""
)
