// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export * from "./getPipeline";
export * from "./getTeam";
export * from "./getTeams";
export * from "./pipeline";
export * from "./provider";
export * from "./team";

// Export sub-modules:
import * as config from "./config";

export {
    config,
};

// Import resources to register:
import { Pipeline } from "./pipeline";
import { Team } from "./team";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "concourse:index/pipeline:Pipeline":
                return new Pipeline(name, <any>undefined, { urn })
            case "concourse:index/team:Team":
                return new Team(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("concourse", "index/pipeline", _module)
pulumi.runtime.registerResourceModule("concourse", "index/team", _module)

import { Provider } from "./provider";

pulumi.runtime.registerResourcePackage("concourse", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:concourse") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
