// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The provider type for the concourse package. By default, resources use package-wide configuration
 * settings, however an explicit `Provider` instance may be created and passed during resource
 * construction to achieve fine-grained programmatic control over provider settings. See the
 * [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'concourse';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Provider.__pulumiType;
    }

    /**
     * Password, do not use if using target
     */
    public readonly password!: pulumi.Output<string | undefined>;
    /**
     * Target as in 'fly --target', do not use if using team/username/password
     */
    public readonly target!: pulumi.Output<string | undefined>;
    /**
     * Team name, do not use if using target
     */
    public readonly team!: pulumi.Output<string | undefined>;
    /**
     * URL, do not use if using target
     */
    public readonly url!: pulumi.Output<string | undefined>;
    /**
     * Username, do not use if using target
     */
    public readonly username!: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["password"] = args ? args.password : undefined;
            resourceInputs["target"] = args ? args.target : undefined;
            resourceInputs["team"] = args ? args.team : undefined;
            resourceInputs["url"] = args ? args.url : undefined;
            resourceInputs["username"] = args ? args.username : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * Password, do not use if using target
     */
    password?: pulumi.Input<string>;
    /**
     * Target as in 'fly --target', do not use if using team/username/password
     */
    target?: pulumi.Input<string>;
    /**
     * Team name, do not use if using target
     */
    team?: pulumi.Input<string>;
    /**
     * URL, do not use if using target
     */
    url?: pulumi.Input<string>;
    /**
     * Username, do not use if using target
     */
    username?: pulumi.Input<string>;
}
